import Link from "next/link";
import { LegalPage } from "@/components/legal/LegalPage";
import {
  COMPANY_EMAIL,
  COMPANY_PHONE_DISPLAY,
  COMPANY_PHONE_TEL,
  LEGAL_LAST_UPDATED,
  createPageMetadata,
} from "@/lib/site";
import { MENNIE_NAME } from "@/lib/mennie";

export const metadata = createPageMetadata({
  title: "Privacy Policy",
  description:
    "How Praverse Tech collects, uses, and protects information submitted through the website and product interest forms.",
  path: "/privacy",
});

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      description="This policy explains how Praverse Tech collects and uses information from the public website, contact requests, product interest forms, and newsletter signups."
      lastUpdated={LEGAL_LAST_UPDATED}
      eyebrow="Privacy & Data Use"
      sections={[
        { id: "scope", label: "Scope" },
        { id: "collect", label: "Information We Collect" },
        { id: "use", label: "How We Use Information" },
        { id: "storage", label: "Storage and Processing" },
        { id: "sharing", label: "How We Share Information" },
        { id: "cookies", label: "Cookies and Analytics" },
        { id: "retention", label: "Retention" },
        { id: "rights", label: "Your Choices" },
        { id: "contact", label: "Contact Us" },
      ]}
      relatedLinks={[
        { href: "/terms", label: "Terms of Service" },
        { href: "/contact", label: "Contact Us" },
      ]}
    >
      <h2 id="scope">1. Scope</h2>
      <p>
        This Privacy Policy applies to information collected through
        praversetech.com, including the contact form, newsletter signup,
        innovation submission workflow, and {MENNIE_NAME} interest or briefing
        forms.
      </p>

      <h2 id="collect">2. Information We Collect</h2>
      <ul>
        <li>
          Contact details you submit, such as your name, email address,
          organization, role, and phone or project context where provided.
        </li>
        <li>
          Business information you choose to share through contact, project, or
          innovation inquiry forms.
        </li>
        <li>
          {MENNIE_NAME} waitlist, media, and briefing request details submitted
          through dedicated product forms.
        </li>
        <li>
          Limited technical information that may be generated by normal website
          requests, such as browser or device metadata sent by your browser.
        </li>
      </ul>

      <h2 id="use">3. How We Use Information</h2>
      <ul>
        <li>To respond to inquiries and evaluate project or partnership requests.</li>
        <li>To manage newsletter subscriptions and relevant follow-up communications.</li>
        <li>To review innovation submissions and {MENNIE_NAME}-related requests.</li>
        <li>To operate, secure, and improve our website and service workflows.</li>
      </ul>

      <h2 id="storage">4. Storage and Processing</h2>
      <p>
        Form submissions are processed through our application workflows and may
        be stored in managed infrastructure used by Praverse Tech for business
        operations. We restrict access to submitted information to authorized
        personnel and service components needed to review and respond.
      </p>

      <h2 id="sharing">5. How We Share Information</h2>
      <p>
        We do not sell personal information. We may share information with
        infrastructure or service providers acting on our behalf where required
        to operate the website or respond to your request, subject to
        appropriate confidentiality and security controls.
      </p>

      <h2 id="cookies">6. Cookies and Analytics</h2>
      <p>
        The public website does not currently use third-party advertising or
        analytics trackers. Some essential browser storage or cookies may be
        used for interface behavior where required for site functionality.
      </p>

      <h2 id="retention">7. Retention</h2>
      <p>
        We retain submitted information for as long as reasonably necessary to
        respond to inquiries, manage ongoing discussions, maintain records, or
        meet legal and operational obligations.
      </p>

      <h2 id="rights">8. Your Choices</h2>
      <p>
        You may request access, correction, or deletion of information you have
        submitted to us, subject to applicable legal and operational
        requirements.
      </p>

      <h2 id="contact">9. Contact Us</h2>
      <p>
        Questions about this policy can be sent to{" "}
        <a href={`mailto:${COMPANY_EMAIL}`}>{COMPANY_EMAIL}</a> or by phone at{" "}
        <a href={COMPANY_PHONE_TEL}>{COMPANY_PHONE_DISPLAY}</a>. You can also
        use our <Link href="/contact">contact page</Link>.
      </p>
    </LegalPage>
  );
}
